# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  SOLUTION_FILE_PATH: Plugins2\Futile.SpecFlow.Actions.sln
  BUILD_CONFIGURATION: Release

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

   # - name: Restore dependencies
   #   run: dotnet restore Plugins2\Futile.SpecFlow.Actions.sln

    - name: Build
      run: dotnet build --no-restore Plugins2\Futile.SpecFlow.Actions.sln

    - name: Test
      run: dotnet test Plugins\SpecFlow.Actions.Configuration\SpecFlow.Actions.Configuration.Tests\SpecFlow.Actions.Configuration.Tests.csproj --no-build --verbosity normal
